# Generated by Django 4.0.4 on 2022-05-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[('PROFESSOR', 'Professor'), ('STUDENT', 'Student')], null=True),
        ),
    ]
