# Generated by Django 4.0.4 on 2022-05-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PROFESSOR', 'Professor'), ('STUDENT', 'Student')], max_length=20, null=True),
        ),
    ]
