# Generated by Django 4.0.4 on 2022-05-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_professor_email_remove_professor_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PROFESSOR', 'Professor'), ('STUDENT', 'Student'), ('ADMIN', 'Admin')], default='ADMIN', max_length=20),
        ),
    ]
