# Generated by Django 4.0.4 on 2022-05-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Student', 'Student'), ('Admin', 'Admin')], default='Admin', max_length=20),
        ),
    ]
