# Generated by Django 4.0.4 on 2022-05-16 19:37

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_expires_at_assignment_due_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='expires_at_gt_created_at',
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(check=models.Q(('due_at__gt', django.db.models.expressions.F('created_at'))), name='due_at_gt_created_at'),
        ),
    ]
