# Generated by Django 4.0.4 on 2022-05-16 19:38

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_assignment_expires_at_gt_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='due_at_gt_created_at',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='due_at',
            new_name='due_date',
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(check=models.Q(('due_date__gt', django.db.models.expressions.F('created_at'))), name='due_date_gt_created_at'),
        ),
    ]
