# Generated by Django 4.0.4 on 2022-05-17 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_assignment_due_at_gt_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='assignment',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.assignment'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
